#!/usr/bin/env node
// Traceability, both ways (gate G3):
//   requirement -> test : every enforced criterion is exercised by a tagged test
//   test -> requirement : every tag in a test names a criterion that exists
// and "deferred" is never free: it must point at an open, owned risk.
//
//   node quality/gate/traceability.mjs            check
//   node quality/gate/traceability.mjs --write    regenerate the matrix
import { writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { ROOT, AC_FILE, read, repoFiles, parseCriteria, testTags, loadRisks, report } from "./lib.mjs";

const MATRIX = "assessment/traceability-matrix.md";

export function checkTraceability({ criteria, tags, risks }) {
  const problems = [];
  const riskById = Object.fromEntries(risks.map((r) => [r.id, r]));

  for (const c of Object.values(criteria)) {
    if (!c.status) problems.push(`${c.id} has no "Status: enforced|deferred" line`);
    if (!c.source) problems.push(`${c.id} has no "Source:" line`);
    if (c.status === "enforced" && !tags[c.id]) {
      problems.push(`${c.id} is enforced but no test is tagged [${c.id}] (${c.title})`);
    }
    if (c.status === "deferred") {
      const risk = c.risk && riskById[c.risk];
      if (!risk) problems.push(`${c.id} is deferred without a risk-register entry`);
      else if (risk.status === "fixed") {
        problems.push(`${c.id} is deferred but ${risk.id} is marked fixed: enforce it or reopen the risk`);
      }
    }
  }
  for (const [id, files] of Object.entries(tags)) {
    if (!criteria[id]) problems.push(`${files[0]} is tagged [${id}], which is not in ${AC_FILE}`);
  }
  for (const r of risks) {
    for (const id of r.acs ?? []) {
      if (!criteria[id]) problems.push(`${r.id} cites ${id}, which is not in ${AC_FILE}`);
    }
    if (r.status === "fixed") {
      const proven = (r.acs ?? []).some((id) => criteria[id]?.status === "enforced" && tags[id]);
      if (!proven) problems.push(`${r.id} is marked fixed but no enforced, tested criterion backs it`);
    }
  }
  return problems;
}

export function renderMatrix({ criteria, tags, risks }) {
  const riskFor = (id) => risks.filter((r) => (r.acs ?? []).includes(id)).map((r) => r.id).join(", ") || "—";
  const rows = Object.values(criteria).map((c) => {
    const tests = (tags[c.id] ?? []).map((f) => `\`${f}\``).join("<br>") || "—";
    const status = c.status === "enforced" ? "enforced" : `deferred (${c.risk ?? "?"})`;
    return `| ${c.id} | ${c.title} | ${c.source} | ${status} | ${tests} | ${riskFor(c.id)} |`;
  });
  const enforced = Object.values(criteria).filter((c) => c.status === "enforced").length;
  return [
    "# Traceability matrix",
    "",
    "Generated by `node quality/gate/traceability.mjs --write`. Do not edit by hand:",
    "CI regenerates it and fails if this file is out of date.",
    "",
    `${Object.keys(criteria).length} criteria: ${enforced} enforced by tests, ` +
      `${Object.keys(criteria).length - enforced} deferred with an open risk.`,
    "",
    "| Criterion | What it requires | Source | Status | Tests | Risks |",
    "|---|---|---|---|---|---|",
    ...rows,
    "",
  ].join("\n");
}

export function collect(root = ROOT) {
  return {
    criteria: parseCriteria(read(AC_FILE, root)),
    tags: testTags(repoFiles(root), root),
    risks: loadRisks(root),
  };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const data = collect();
  const matrix = renderMatrix(data);
  if (process.argv.includes("--write")) {
    writeFileSync(path.join(ROOT, MATRIX), matrix);
    console.log(`wrote ${MATRIX}`);
  }
  const problems = checkTraceability(data);
  let current = "";
  try {
    current = read(MATRIX);
  } catch {
    /* reported below */
  }
  if (current !== matrix) problems.push(`${MATRIX} is out of date: run "node quality/gate/traceability.mjs --write"`);
  const enforced = Object.values(data.criteria).filter((c) => c.status === "enforced").length;
  process.exit(
    report("Traceability", problems, `${enforced} enforced criteria each have a test; every test tag resolves`)
  );
}
